accountability/urls.py
"""Определяет схемы URL для Accountability."""

from django.conf.urls import url
from . import views


urlpatterns = [
    # Страница отчетности
    url(r'^accountability', views.accountability, name='accountability'),
    url(r'^statistic_xls', views.statistic_xls, name='statistic_xls'),
]

cardindex/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('main.urls', namespace='main')),
    url(r'^users/', include('users.urls', namespace='users')),
    url(r'^accountability/', include('accountability.urls', namespace='accountability')),

]

main/urls.py
"""Определяет схемы URL для MAIN."""

from django.conf.urls import url
from . import views
from accountability.views import statistic_xls as statistic_xls

urlpatterns = [
    # Домашняя страница
    url(r'^$', views.main, name='main'),
    url(r'^index$', views.index, name='index'),
    url(r'^archiv$', views.search, name='search'),
    url(r'^archiv/(?P<ld_id>\d+)/$', views.ld, name='ld'),
    url(r'editld/(?P<ld_id>\d+)/$', views.edit_ld, name='edit_ld'),
    url(r'^injob$', views.ldinjob, name='ldinjob'),
    url(r'^newld$', views.newld, name='newld'),
    url(r'^newclient$', views.newclient, name='newclient'),
    url(r'^queryld$', views.queryld, name='queryld'),
    url(r'^archiv_querys$', views.archiv_querys, name='archiv_querys'),
    url(r'^archiv_querys/(?P<query_ipd>\d+)/$', views.queryld, name='queryld'),
    url(r'^statistic_xls', statistic_xls, name='statistic_xls'),

]

accountability/models.py
from django.db import models

# Create your models here.

accountability/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse
from django.views.decorators.csrf import csrf_exempt

from main.views import *
from users.views import *

# Create your views here.

def accountability(request):
    '''Формирование отчетов'''
    lds = CardIndex.objects.all()
    querys = Query.objects.all()
    return render(request, 'accountability/accountability.html', {'lds': lds, 'querys': querys})

@csrf_exempt
@login_required
def statistic_xls(request):
    """ Генерация отчетов в формате XLS """
    import xlwt

    wb = xlwt.Workbook(encoding='utf-8')
    response = HttpResponse(content_type='application/ms-excel')

    if request.method == "POST":
        pk = request.POST["pk"]  # Первичный ключ
        tp = request.POST["type"]  # Тип статистики

    else:
        pk = request.GET["pk"]  # Первичный ключ
        tp = request.GET["type"]  # Тип статистики

    symbols = (u"абвгдеёжзийклмнопрстуфхцчшщъыьэюяАБВГДЕЁЖЗИЙКЛМНОПРСТУФХЦЧШЩЪЫЬЭЮЯ",
               u"abvgdeejzijklmnoprstufhzcss_y_euaABVGDEEJZIJKLMNOPRSTUFHZCSS_Y_EUA")  # Словарь для транслитерации
    tr = {ord(a): ord(b) for a, b in zip(*symbols)}  # Перевод словаря для транслита

    borders = xlwt.Borders()
    borders.left = xlwt.Borders.THIN
    borders.right = xlwt.Borders.THIN
    borders.top = xlwt.Borders.THIN
    borders.bottom = xlwt.Borders.THIN

    if tp == "all_ld":
        # Формирование отчетов по всем ЛД для архивариуса

        lds = CardIndex.objects.all()
        response['Content-Disposition'] = str.translate(
            "attachment; filename='Отчет по количеству действующих ЛД.xls'".format(), tr)
        ws = wb.add_sheet('Всего ЛД в картотеке')

        font_style_wrap = xlwt.XFStyle()
        font_style_wrap.alignment.wrap = 1
        font_style_wrap.borders = borders
        font_style = xlwt.XFStyle()
        font_style.borders = borders

        row_i = 0
        row = [
            ('ИПД', 4000),
            ('ФИО', 7000),
            ('Контроль', 5500),
            ('Специалист', 9000),
        ]

        for i in range(len(row)):
            ws.write(row_i, i, row[i][0], font_style_wrap)
            ws.col(i).width = row[i][1]

        row_i = 1

        for ld in lds:
            if ld.spec == None:
                row = [
                    str(ld.ipd),
                    str(ld.client),
                    str(ld.control),
                    'не назначен'
                ]
            else:
                row = [
                    str(ld.ipd),
                    str(ld.client),
                    str(ld.control),
                    str(ld.spec)
                ]
            for i in range(len(row)):
                ws.write(row_i, i, row[i], font_style_wrap)
            row_i += 1

    if tp == "spec":
        # Формирование отчетов по специалистам

        specs = CardIndex.objects.filter(spec=pk)
        response['Content-Disposition'] = str.translate(
            "attachment; filename='Отчет по специалисту.xls'".format(), tr)


        ws = wb.add_sheet("ЛД в работе")

        font_style_wrap = xlwt.XFStyle()
        font_style_wrap.alignment.wrap = 1
        font_style_wrap.borders = borders
        font_style = xlwt.XFStyle()
        font_style.borders = borders
        row_i = 0
        row = [
            ('ИПД', 4000),
            ('ФИО', 7000),
            ('Адрес', 10000),
            ('Статус', 5500),
            ('Специалист', 9000),
        ]

        for i in range(len(row)):
            ws.write(row_i, i, row[i][0], font_style_wrap)
            ws.col(i).width = row[i][1]

        row_i += 1

        for s in specs:
            row_s = [
                str(s.ipd),
                str(s.client),
                str(s.client.address),
                str(s.category),
                str(s.spec),
            ]
            for i in range(len(row_s)):
                ws.write(row_i, i, row_s[i], font_style_wrap)
            row_i += 1

    if tp == "archiv":
        # Формирование отчетов находищихся в архиве

        archiv = CardIndex.objects.filter(control__id=6)
        response['Content-Disposition'] = str.translate(
            "attachment; filename='Отчет ЛД находящихся в архиве.xls'".format(), tr)


        ws = wb.add_sheet("ЛД в архиве")

        font_style_wrap = xlwt.XFStyle()
        font_style_wrap.alignment.wrap = 1
        font_style_wrap.borders = borders
        font_style = xlwt.XFStyle()
        font_style.borders = borders
        row_i = 0
        row = [
            ('ИПД', 4000),
            ('ФИО', 7000),
            ('Адрес', 10000),
            ('Статус', 5500),
            ('Движение ЛД', 4000),
        ]

        for i in range(len(row)):
            ws.write(row_i, i, row[i][0], font_style_wrap)
            ws.col(i).width = row[i][1]

        row_i += 1

        for arch in archiv:
            row_s = [
                str(arch.ipd),
                str(arch.client),
                str(arch.client.address),
                str(arch.category),
                str(arch.control),
            ]
            for i in range(len(row_s)):
                ws.write(row_i, i, row_s[i], font_style_wrap)
            row_i += 1

    if tp == "offsite":
        # Формирование отчетов находящихся в др. уч.

        offsite = CardIndex.objects.filter(control__id=3)
        response['Content-Disposition'] = str.translate(
            "attachment; filename='Отчет ЛД находящихся в других учреждениях.xls'".format(), tr)


        ws = wb.add_sheet("ЛД в др. уч.")

        font_style_wrap = xlwt.XFStyle()
        font_style_wrap.alignment.wrap = 1
        font_style_wrap.borders = borders
        font_style = xlwt.XFStyle()
        font_style.borders = borders
        row_i = 0
        row = [
            ('ИПД', 4000),
            ('ФИО', 7000),
            ('Адрес', 10000),
            ('Статус', 5500),
            ('Движение ЛД', 5000),
        ]

        for i in range(len(row)):
            ws.write(row_i, i, row[i][0], font_style_wrap)
            ws.col(i).width = row[i][1]

        row_i += 1

        for off in offsite:
            row_s = [
                str(off.ipd),
                str(off.client),
                str(off.client.address),
                str(off.category),
                str(off.control),
            ]
            for i in range(len(row_s)):
                ws.write(row_i, i, row_s[i], font_style_wrap)
            row_i += 1

    wb.save(response)
    return response

accountability/templates/accountability/accountability.html
{% extends "main/base.html" %}
{% block title %}
    {% block name %} | Отчетность{% endblock name %}
{% endblock title%}
{% block menu %}
    <a class="navbar-brand" href="{% url 'main:main' %}">Поиск ЛД</a>
    <a class="navbar-brand" href="{% url 'main:newclient' %}">Добавить нового клиента</a>
    <a class="navbar-brand" href="{% url 'main:newld' %}">Добавить нового ЛД</a>
{% endblock menu %}
{% block content %}
<div class="container">
<div id="form">Отчетность</div><br>
    <hr>
    <div class="row" id="li">
        <div class="col-xs-6">
            <div class="panel panel-default panel-flt">
                <div class="panel-heading">
                    <h3 class="panel-title">Отчет по количеству действующих ЛД</h3>
                </div>
                <ul class="list-group">
                    {% for ld in lds %}
                        {% if request.user.is_superuser %}
                            <li class="list-group-item" onclick="gen_stat('all_ld', {{ ld.pk }})">Получить</li>
                        {% else %}
                            {% if ld.pk == request.user.usersprofile.pk %}
                                <li class="list-group-item" onclick="gen_stat('all_ld', {{ ld.pk }})">Получить</li>
                            {% endif %}
                        {% endif %}
                    {% endfor %}
                </ul>
            </div>
        </div>
        <div class="col-xs-6">
            <div class="panel panel-default panel-flt">
                <div class="panel-heading">
                    <h3 class="panel-title">Отчет ЛД, находящихся у специалиста</h3>
                </div>
                <ul class="list-group">
                    {% for ld in lds %}
                        {% if request.user.is_superuser %}
                            <li class="list-group-item" onclick="gen_stat('spec', {{ ld.pk }})">Получить</li>
                        {% else %}
                            {% if ld.pk == request.user.usersprofile.pk %}
                                <li class="list-group-item" onclick="gen_stat('spec', {{ ld.pk }})">Получить</li>
                            {% endif %}
                        {% endif %}
                    {% endfor %}
                </ul>
            </div>
        </div>
        <div class="col-xs-6">
            <div class="panel panel-default panel-flt">
                <div class="panel-heading">
                    <h3 class="panel-title">Отчет ЛД, находящихся в архиве</h3>
                </div>
                <ul class="list-group">
                    {% for ld in lds %}
                        {% if request.user.is_superuser %}
                            <li class="list-group-item" onclick="gen_stat('archiv', {{ ld.pk }})">Получить</li>
                        {% else %}
                            {% if ld.pk == request.user.usersprofile.pk %}
                                <li class="list-group-item" onclick="gen_stat('archiv', {{ ld.pk }})">Получить</li>
                            {% endif %}
                        {% endif %}
                    {% endfor %}
                </ul>
            </div>
        </div>
        <div class="col-xs-6">
            <div class="panel panel-default panel-flt">
                <div class="panel-heading">
                    <h3 class="panel-title">Отчет ЛД, находящихся в других учреждениях</h3>
                </div>
                <ul class="list-group">
                    {% for ld in lds %}
                        {% if request.user.is_superuser %}
                            <li class="list-group-item" onclick="gen_stat('offsite', {{ ld.pk }})">Получить</li>
                        {% else %}
                            {% if ld.pk == request.user.usersprofile.pk %}
                                <li class="list-group-item" onclick="gen_stat('offsite', {{ ld.pk }})">Получить</li>
                            {% endif %}
                        {% endif %}
                    {% endfor %}
                </ul>
            </div>
        </div>
    </div>
</div>

{% endblock content %}
{% block scripts %}
    <script src="/static/js/bootstrap-datepicker.min.js"></script>
    <script>
        function gen_stat(stype, pk) {
            window.open('statistic_xls?type=' + stype + "&pk=" + pk, '_blank');
        }
    </script>
{% endblock scripts %}