cardindex/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('main.urls', namespace='main')),
    url(r'^users/', include('users.urls', namespace='users')),
    url(r'^accountability/', include('accountability.urls', namespace='accountability')),

]

main/urls.py
"""Определяет схемы URL для MAIN."""

from django.conf.urls import url
from . import views
from accountability.views import statistic_xls as statistic_xls

urlpatterns = [
    # Домашняя страница
    url(r'^$', views.main, name='main'),
    url(r'^index$', views.index, name='index'),
    url(r'^archiv$', views.search, name='search'),
    url(r'^archiv/(?P<ld_id>\d+)/$', views.ld, name='ld'),
    url(r'editld/(?P<ld_id>\d+)/$', views.edit_ld, name='edit_ld'),
    url(r'^injob$', views.ldinjob, name='ldinjob'),
    url(r'^newld$', views.newld, name='newld'),
    url(r'^newclient$', views.newclient, name='newclient'),
    url(r'^queryld$', views.queryld, name='queryld'),
    url(r'^archiv_querys$', views.archiv_querys, name='archiv_querys'),
    url(r'^archiv_querys/(?P<query_ipd>\d+)/$', views.queryld, name='queryld'),
    url(r'^statistic_xls', statistic_xls, name='statistic_xls'),

]

users/urls.py
"""Определяет схемы URL для пользователей"""
from django.conf.urls import url
from django.contrib.auth.views import login
from . import views

urlpatterns = [
    # Страница входа
    url(r'^login/$', login, {'template_name': 'users/login.html'}, name='login'),
    # Страница выхода
    url(r'^logout/$', views.logout_view, name='logout'),
]

users/models.py
from django.db import models

# Create your models here.
from django.db import models
from django.contrib.auth.models import User


class UsersProfile(models.Model):
    """
    Профили сотрудников
    """

    user = models.OneToOneField(User, null=True, blank=True, help_text='Ссылка на Django-аккаунт')
    fio = models.CharField(max_length=255, help_text='ФИО')


    def get_fio(self, dots=True):
        """
        Функция формирования фамилии и инициалов (Иванов И.И.)
        :param dots:
        :return:
        """
        fio = self.fio.replace("  ", " ").strip()
        fio_split = fio.split(" ")

        if len(fio_split) == 0:
            fio_split.append("")
        if len(fio_split) == 1:
            fio_split.append("")
        if len(fio_split) == 2:
            fio_split.append("")

        if dots:
            return fio_split[0] + " " + fio_split[1][0] + "." + fio_split[2][0] + "."
        return fio_split[0] + " " + fio_split[1][0] + fio_split[2][0]


    def is_member(self, groups: list) -> bool:
        """
        Проверка вхождения пользователя в группу
        :param group: название группы
        :return: bool, входит ли в указаную группу
        """
        return self.user.groups.filter(name__in=groups).exists()

    def __str__(self):  # Получение фио при конвертации объекта UsersProfile в строку
        return self.fio

users/views.py
from django.shortcuts import render

# Create your views here.

from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse
from django.contrib.auth import logout

def logout_view(request):
    """Завершает сеанс работы с приложением."""
    logout(request)
    return HttpResponseRedirect(reverse('main:main'))

users/templates/users/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>
        Картотека личных дел ОГКУ "УСЗН по Заларинскому району"{% block name %}{% endblock name %}
    </title>
    <link rel="shortcut icon" href="static/img/favicon.ico" type="image/png">
    <link href="/static/css/bootstrap.min.css" rel="stylesheet">
    <link href="/static/bootflat/css/bootflat.min.css" rel="stylesheet">
    <!--[if lt IE 9]>
           <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
           <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
      <![endif]-->

</head>
<body>
{% block content %}{% endblock content %}
<script src="/static/js/jquery.min.js"></script>
<script src="/static/js/bootstrap.min.js"></script>
</body>
</html>

users/templates/users/login.html
{% extends "users/base.html" %}
{% block title %}
    {% block name %} | Авторизация{% endblock name %}
{% endblock title%}
{% block content %}
<div class="container">
    <div style="text-align: center">
        <h1 style="font-weight: 300;margin-bottom: 20px;font-size: 26pt">
            Картотека личных дел ОГКУ "УСЗН по Заларинскому району</h1>
    </div>
    {% if error %}
        <div class="alert alert-danger alert-dismissable" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
            Неверный логин или пароль
        </div>
    {% endif %}
    <form class="form-signin" action="{% url 'users:login' %}" method='POST'>
        {% csrf_token %}
        <div class="panel panel-flt">
            <div class="panel-heading" style="font-size: 16pt">Авторизация</div>
            <div class="panel-body">
                <input type="text" id="inputLogin" class="form-control" name='username' placeholder="Логин"
                       value="{{ username }}" required autofocus>
                <input type="password" id="inputPassword" class="form-control" name='password' placeholder="Пароль"
                       required>
                <input type="hidden" name="next" value="{% url 'main:main' %}" />
                <button class="btn btn-lg btn-primary btn-block" type="submit" style="height: 40px;
                width: auto;">Вход</button>
            </div>
        </div>
    </form>
</div>
    <style>

        @font-face {
            font-family: 'Open Sans';
            font-style: normal;
            font-weight: 300;
            src: local('Open Sans Light'), local('OpenSans-Light'), url(/static/fonts/OpenSans/OpenSans-Light.ttf);
        }

        @font-face {
            font-family: 'Open Sans';
            font-style: normal;
            font-weight: 400;
            src: local('Open Sans'), local('OpenSans'), url(/static/fonts/OpenSans/OpenSans-Regular.ttf)
        }

        @font-face {
            font-family: 'Open Sans';
            font-style: normal;
            font-weight: 700;
            src: local('Open Sans Bold'), local('OpenSans-Bold'), url(/static/fonts/OpenSans/OpenSans-Bold.ttf)
        }

        input:-webkit-autofill {
            -webkit-box-shadow: 0 0 0px 1000px white inset !important;
        }
.panel-flt{
    background: transparent;
}
        .panel-flt .panel-heading {
            background-color: #95A5A6;
            color: #fff
            height: 30px;
            text-align: center;
            padding-top: 10px;
        }

        .panel-flt .panel-title {
            color: #fff !important;
        }
        .panel-flt .panel-body{
            border-radius: 0 0 4px 4px;
            background: rgba(255,255,255,.5)!important;
            margin-top: 15px;
            position: absolute;
            display: grid;
            width: 450px;
        }

        .panel-flt .panel-body, .panel-flt .list-group-item {
            background-color: #ECF0F1;
        }
        .panel-flt input{
            background: rgba(255,255,255,.5)!important;
        }

        .btn-primary {
            background: #6C7A89;
            border: 0
        }

        .btn-primary:hover, .btn-primary:active, .btn-primary:focus {
            background: #049372;
            border: 0
        }
        body {
            background: #f0f0f0;
        }

        .form-signin {
            max-width: 450px;
            margin: 0 auto;
        }

        .form-signin-heading {
            margin-top: 0;
        }
        .form-signin .form-signin-heading,
        .form-signin .checkbox {
            margin-bottom: 10px;
        }

        .form-signin .checkbox {
            font-weight: normal;
        }

        .form-signin .form-control {
            position: relative;
            height: auto;
            -webkit-box-sizing: border-box;
            -moz-box-sizing: border-box;
            box-sizing: border-box;
            padding: 10px;
            font-size: 16px;
            border-radius: 5px 5px 0 0;
        }


        .form-signin .form-control:focus {
            z-index: 2;
        }

        .form-signin input[type="email"] {
            margin-bottom: -1px;
            border-bottom-right-radius: 0;
            border-bottom-left-radius: 0;
        }

        .form-signin input[type="password"] {
            margin-bottom: 10px;
            border-radius: 0 0 5px 5px;
        }
    </style>
{% endblock %}