accountability/urls.py
"""Определяет схемы URL для Accountability."""

from django.conf.urls import url
from . import views


urlpatterns = [
    # Страница отчетности
    url(r'^accountability', views.accountability, name='accountability'),
    url(r'^statistic_xls', views.statistic_xls, name='statistic_xls'),
]

cardindex/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('main.urls', namespace='main')),
    url(r'^users/', include('users.urls', namespace='users')),
    url(r'^accountability/', include('accountability.urls', namespace='accountability')),

]

main/urls.py
"""Определяет схемы URL для MAIN."""

from django.conf.urls import url
from . import views
from accountability.views import statistic_xls as statistic_xls

urlpatterns = [
    # Домашняя страница
    url(r'^$', views.main, name='main'),
    url(r'^index$', views.index, name='index'),
    url(r'^archiv$', views.search, name='search'),
    url(r'^archiv/(?P<ld_id>\d+)/$', views.ld, name='ld'),
    url(r'editld/(?P<ld_id>\d+)/$', views.edit_ld, name='edit_ld'),
    url(r'^injob$', views.ldinjob, name='ldinjob'),
    url(r'^newld$', views.newld, name='newld'),
    url(r'^newclient$', views.newclient, name='newclient'),
    url(r'^queryld$', views.queryld, name='queryld'),
    url(r'^archiv_querys$', views.archiv_querys, name='archiv_querys'),
    url(r'^archiv_querys/(?P<query_ipd>\d+)/$', views.queryld, name='queryld'),
    url(r'^statistic_xls', statistic_xls, name='statistic_xls'),

]

users/urls.py
"""Определяет схемы URL для пользователей"""
from django.conf.urls import url
from django.contrib.auth.views import login
from . import views

urlpatterns = [
    # Страница входа
    url(r'^login/$', login, {'template_name': 'users/login.html'}, name='login'),
    # Страница выхода
    url(r'^logout/$', views.logout_view, name='logout'),
]

main/models.py
# coding=utf-8
from django.db import models
from users.models import UsersProfile

# Create your models here.

class Client(models.Model):
    """
    Личное дело клиента
    """
    last_name = models.CharField(max_length=30, help_text='Фамилия') # Фамилия
    first_name = models.CharField(max_length=30, help_text='Имя') # Имя
    middle_name = models.CharField(max_length=30, help_text='Отчество') # Отчество
    bday = models.DateField(auto_now=False, auto_now_add=False, help_text='Дата рождения') # Дата рождения
    address = models.CharField(max_length=100, help_text='Адрес проживания') # Адрес проживания

    def fio(self) -> str:
        """
        Функция возврата полного ФИО
        :return: Полное ФИО
        """
        return '{} {} {}'.format(self.last_name, self.first_name, self.middle_name)

    def shortfio(self, supershort=False) -> str:
        """
        Функция возврата сокращенного ФИО
        :return: Короткое ФИО
        """
        if self.middle_name and len(self.middle_name) > 0:
            r = '{} {}.{}.'.format(self.last_name, self.first_name[0], self.middle_name[0])
        else:
            r = '{} {}.'.format(self.last_name, self.first_name[0])
        if supershort:
            r = r.replace(". ", "").replace(".", "")
        return r

    def __str__(self):
        return self.fio()


class Category(models.Model):
    """
    Категория клиента
    """
    category = models.CharField(max_length=40, help_text='Категория клиента')  # Категория граждан

    def __str__(self):
        return self.category


class Control(models.Model):
    """
    Контроль за передвижением ЛД
    """
    check_mark = models.CharField(max_length=30, help_text='Движение ЛД') # Перемещение ЛД

    def __str__(self):
        return self.check_mark


class CardIndex(models.Model):
    """
    Личное дело
    """
    ipd = models.IntegerField(verbose_name='Индивидуальное порядковое дело', help_text='ИПД')
    client = models.ForeignKey(Client, verbose_name='Клиент', help_text='Клиент')
    category = models.ForeignKey(Category, verbose_name='Категория клиента', help_text='Категория клиента')
    control = models.ForeignKey(Control, verbose_name='Статус ЛД', help_text='Статус ЛД')
    spec = models.ForeignKey(UsersProfile, default=0, blank=True, null=True,
                             verbose_name='Движение ЛД по специалистам', help_text='Движение ЛД')
    info = models.CharField(max_length=200, blank=True, verbose_name='Движение ЛД по другим УСЗН',
                            help_text='Движение по др. УСЗН.')

    def __str__(self):
        return '{} {}'.format(self.ipd, self.client)

class Query(models.Model):
    """
    Запрос специалиста на работу с ЛД
    """
    query_client = models.ForeignKey(CardIndex, null=True, help_text='* Личное дело')
    query_spec = models.ForeignKey(UsersProfile, null=True, help_text='* Специалист')
    query_ld = models.BooleanField(default=False, blank=False, help_text='* Статус запроса')
    query_date = models.DateField(default=None, null=True, help_text='* Дата запроса (01.01.2019)')

main/forms.py
from django import forms
from main.models import *

class AddControl(forms.ModelForm):
    class Meta:
        model = Control
        fields = [
            'check_mark',
        ]

        labels = {
            'check_mark': ''
        }

class AddCategory(forms.ModelForm):
    class Meta:
        model = Category
        fields = [
            'category',
        ]

        labels = {
            'category': ''
        }

class AddClientForm(forms.ModelForm):
    class Meta:
        model = Client
        fields = [
            'last_name',
            'first_name',
            'middle_name',
            'bday',
            'address'

        ]
        labels = {
            'last_name': '',
            'first_name': '',
            'middle_name': '',
            'bday': '',
            'address': ''
        }


class AddLdForm(forms.ModelForm):
    class Meta:
        model = CardIndex
        fields = [
            'ipd',
            'client',
            'control',
            'category',
            'spec',
            'info',
        ]
        labels = {
            'client': '',
            'control': '',
            'category': '',
            'ipd': '',
            'info': '',
            'spec': ''
        }

class AddQueryLdForm(forms.ModelForm):
    class Meta:
        model = Query
        fields = [
            'query_client',
            'query_date',
            'query_ld',
            'query_spec'
        ]

        labels = {
            'query_client': '',
            'query_date': '',
            'query_ld': '',
            'query_spec': ''
        }

class EditLdForm(forms.ModelForm):
    class Meta:
        model = CardIndex
        fields = ['client']
        labels = {'client': ''}
        widgets = {'client': forms.Textarea(attrs={'cols': 50})}

main/views.py
from django.shortcuts import render
from django.core import serializers
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse

import datetime

from main.models import *
from users.models import *
from main.forms import *
from main.decorators import group_required
from users.views import *

# Create your views here.
def index(request):
    """"""
    return render(request, 'main/index.html')

@login_required
def main(request):
    """Домашняя страница картотеки"""
    menu = []
    groups = [str(x) for x in request.user.groups.all()]
    if request.user.is_superuser:
        return render(request, 'main/admin.html')
    if "Архивариус" in groups:
        menu.append(
            {'url': 'main:main', 'title': 'Поиск ЛД'}
        )
        return render(request, 'main/archiv.html', {'menu': menu})
    if "Специалист" in groups:
        return render(request, 'main/spec.html')

@login_required
def search(request):
    '''Поиск информации по базе данных для архивариуса'''
    groups = [str(x) for x in request.user.groups.all()]
    con = Control.objects.all()
    spec = UsersProfile.objects.all()
    if request.method == 'POST' and request.POST['search']:
        query = request.POST['search'].strip()
        if query.isdigit():
            search = CardIndex.objects.filter(ipd = query)
        else:
            split = str(query).split()
            search = CardIndex.objects.filter(client__last_name=split[0].title(),
                                              client__first_name=split[1].title(),
                                              client__middle_name=split[2].title())
        if "Архивариус" in groups:
            return render(request, 'main/archiv.html', {'data_search': search, 'control': con, 'spec': spec})
        if "Специалист" in groups:
            return render(request, 'main/spec.html', {'data_search': search, 'control': con, 'spec': spec})
    else:
        return render(request, 'main/index.html')

@login_required
@group_required("Архивариус")
def ld(request, ld_id):
    """Выводит одну тему и все ее записи."""
    data = CardIndex.objects.get(id=ld_id)
    context = {'ld': data}
    return render(request, 'main/ld.html', context)

@login_required
@group_required("Архивариус")
def edit_ld(request, ld_id):
    """Редактирует существующую запись."""
    ld = CardIndex.objects.get(id=ld_id)
    if request.method != 'POST':
        # Исходный запрос; форма заполняется данными текущей записи.
        form = AddLdForm(instance=ld)
    else:
        # Отправка данных POST; обработать данные.
        form = AddLdForm(instance=ld, data=request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('main:ld', args=[ld.id]))
    context = {'ld': ld, 'form': form}
    return render(request, 'main/editld.html', context)

@login_required
def ldinjob(request):
    """Выводит личные дела в работе специалиста"""
    lds = CardIndex.objects.all()
    injob = CardIndex.objects.filter(spec=request.user.usersprofile).order_by('ipd')
    return render(request, 'main/injob.html', {'injob': injob, 'lds': lds})



@login_required
@group_required("Архивариус")
def newld(request):
    '''Добавление нового ЛД'''
    if request.method != 'POST':
        form = AddLdForm()
    else:
        form = AddLdForm(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('main:main'))

    context = {'form': form}
    return render(request, 'main/newld.html', context)


@login_required
@group_required("Архивариус")
def newclient(request):
    """Добавление нового клиента"""
    if request.method != 'POST':
        form = AddClientForm()
    else:
        form = AddClientForm(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('main:main'))
    context = {'form': form}
    return render(request, 'main/newclient.html', context)

@login_required
def queryld(request):
    '''Функция запроса ЛД'''
    #q = request.user.usersprofile
    users = UsersProfile.objects.all()
    #users = UsersProfile.objects.order_by(q)
    query = CardIndex.objects.all()
    if request.method != 'POST':
        form = AddQueryLdForm()
    else:
        form = AddQueryLdForm(data=request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('main:main'))
    context = {'form': form, 'query': query, 'users': users}
    return render(request, 'main/queryld.html', context)


@login_required
@group_required("Архивариус")
def archiv_querys(request):
    '''Просмотр всех запросов от специалистов'''
    query = Query.objects.filter(query_date=datetime.date.today())
    return render(request, 'main/archiv_querys.html', {'querys': query})

"""
def queryld(request):
    '''Функция запроса ЛД'''
    query = CardIndex.objects.all()

    return render(request, 'main/queryld.html', {'query': query})
"""

def accountability(request):
    '''Отчеты'''
    return render(request, 'main/accountability.html')

main/templates/main/admin.html
{% extends "main/base.html" %}
{% block title %}
    {% block name %} | Рабочее место администратора{% endblock name %}
{% endblock title%}
{% block menu %}
    <a class="navbar-brand" href="http://localhost:8000/admin">Администрирование</a>
{% endblock menu %}

{% block content %}

{% endblock content %}

main/templates/main/archiv.html
{% extends "main/base.html" %}
    {% block title %}
        {% block name %} | Рабочее место архивариуса{% endblock name %}
    {% endblock title%}
{% block menu %}
    <a class="navbar-brand" href="{% url 'main:archiv_querys' %}">Запросы ЛД</a>
    <a class="navbar-brand" href="{% url 'main:newld' %}">Добавить новое ЛД</a>
    <a class="navbar-brand" href="{% url 'main:newclient' %}">Добавить нового клиента</a>
    <a class="navbar-brand" href="{% url 'accountability:accountability' %}">Отчетность</a>
    {% endblock menu %}
{% block content %}
<div class="container-fluid">
    <div class="row" align="right">
        <form action="{% url 'main:search' %}" method="post">
            <div class="col-md-7" style="margin-left: 10px; width: auto;">
                {% csrf_token %}
                {{ form.as_p }}
                <p>
                    <label for="search"></label>
                    <input class="form-control" id="search" type="text" name="search" value="{{ search }}" size="100"
                           placeholder="Поиск личного дела по ФИО или ИПД, например: Иванов Иван Петрович или 123456"
                           title="Поиск личного дела по ФИО или ИПД, например: Иванов Иван Петровичили или 123456">
                </p>
            </div>
            <div class="col-md-1" style="float: right;">
                <button class="btn btn-lg btn-primary btn-block" type="submit">Найти</button>
            </div>
        </form>
    </div>
    <hr>
</div>
<div class="container-fluid">
    <div class="row" align="left">
        <div class="col-md-12">
            <table class="table">
    <thead class="thead-dark">
        <tr>
            <th class="col-xs-1">ИПД</th>
            <th class="col-xs-1">Фамилия</th>
            <th class="col-xs-1">Имя</th>
            <th class="col-xs-1">Отчество</th>
            <th class="col-xs-1">Дата рождения</th>
            <th class="col-xs-2">Адрес</th>
            <th class="col-xs-1">Категория</th>
            <th class="col-xs-1">Статус ЛД</th>
            <th class="col-xs-1">Движение ЛД</th>
            <th id="sel" class="col-xs-1">Изменение ЛД</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td></td>
        </tr>
    </tbody>
    </table>
        </div>
    </div>
</div>
<div class="container-fluid">
    <div class="row" align="left">
        <div class="col-md-12">
        {% for i in data_search %}
            <table class="table">
    <thead class="thead-dark">
    </thead>
    <tbody>
        <tr>
            <th class="col-xs-1"><a href="{% url 'main:edit_ld' i.id %}">{{ i.ipd }}</a></th>
            <td class="col-xs-1">{{ i.client.last_name }}</td>
            <td class="col-xs-1">{{ i.client.first_name }}</td>
            <td class="col-xs-1">{{ i.client.middle_name }}</td>
            <td class="col-xs-1">{{ i.client.bday }}</td>
            <td class="col-xs-2">{{ i.client.address }}</td>
            <td class="col-xs-1">{{ i.category }}</td>
            <td class="col-xs-1">{{ i.control }}</td>
            {% if i.control.id == 6 %}
            <td class="col-xs-1"></td>
            {% elif i.control.id == 3 %}
            <td class="col-xs-1">{{ i.info }}</td>
            {% else %}
            <td class="col-xs-1">{{ i.spec }}</td>
            {% endif %}
            <td class="col-xs-1">
                <a href="{% url 'main:edit_ld' i.id %}" class="btn btn-info">Редактировать ЛД</a>
            </td>
        </tr>
    </tbody>
    </table>
        {% endfor %}
        </div>
    <div id="specialist" onclick="return false" style="display:none">
        <form method="post" action="/">
            {% for i in spec %}
                <input type="checkbox" name="option1" value="a1"> {{ i.fio }}<Br>
            {% endfor %}
            <p><input id="continue" type="submit" value="Отправить"></p>
        </form>
    </div>
    </div>
</div>

{% endblock content %}
{% block scripts %}
<script type="text/javascript" src="http://ajax.googleapis.com/..."></script>
<script type="text/javascript">
$('#sel').on('click',function(){
        $('#specialist').show();
});
</script>
{% endblock scripts %}

main/templates/main/archiv_querys.html
{% extends "main/base.html" %}
{% block title %}
    {% block name %} | Запросы специалистов{% endblock name %}
{% endblock title%}
{% block menu %}
    <a class="navbar-brand" href="{% url 'main:main' %}">Поиск ЛД</a>
    <a class="navbar-brand" href="{% url 'main:newld' %}">Добавить новое ЛД</a>
    <a class="navbar-brand" href="{% url 'main:newclient' %}">Добавить нового клиента</a>
{% endblock menu %}
{% block content %}
<div class="container">
    <div id="form">Список запросов ЛД</div><br>
    {% for q in querys %}
    <ul style="margin-top: 15px;">
        <li>Личное дело: {{ q.query_client }}. Назначить в работу специалисту: {{ q.query_spec }}.
            <div style="float: right;"><a href="{% url 'main:edit_ld' q.query_client.id %}" class="btn btn-info">Назначить ЛД</a></div>
        </li>
    </ul>
    {% endfor %}
</div>
{% endblock content %}

main/templates/main/editld.html
{% extends "main/base.html" %}
{% block title %}
    {% block name %} | Редактирование ЛД{% endblock name %}
{% endblock title%}
{% block menu %}
    <a class="navbar-brand" href="{% url 'main:main' %}">Поиск ЛД</a>
    <a class="navbar-brand" href="{% url 'main:newld' %}">Добавить новое ЛД</a>
    <a class="navbar-brand" href="{% url 'main:newclient' %}">Добавить нового клиента</a>
{% endblock menu %}
{% block content %}
<div class="container">
    <div id="form">Форма редактирования ЛД</div><br>
    <hr>
    <form action="{% url 'main:edit_ld' ld.id %}" method='post'>
        {% csrf_token %}
        <div id="form_style">
            {{ form.as_p }}
            <button class="btn btn-lg btn-primary btn-block" name="submit">Сохранить изменения</button>
        </div>
    </form>
</div>
{% endblock content %}

main/templates/main/index.html
{% extends "main/base.html" %}
{% block title %}
    {% block name %} | Домашнаяя страница{% endblock name %}
{% endblock title%}
{% block menu %}
    <a class="navbar-brand" href="{% url 'main:main' %}">Поиск ЛД</a>
{% endblock menu %}
{% block content %}

{% endblock content %}

main/templates/main/ld.html
{% extends "main/base.html" %}
{% block title %}
    {% block name %} | Личное дело{% endblock name %}
{% endblock title%}
{% block menu %}
    <a class="navbar-brand" href="{% url 'main:main' %}">Поиск ЛД</a>
    <a class="navbar-brand" href="{% url 'main:newld' %}">Добавить новое ЛД</a>
    <a class="navbar-brand" href="{% url 'main:newclient' %}">Добавить нового клиента</a>
{% endblock menu %}
{% block content %}
<div class="container-fluid">
    <div id="table_cont">
        <table class="table table-bordered floatThead ct" id="log_table">
        <thead class="thead-dark">
            <tr>
                <th scope="col">ИПД</th>
                <th scope="col">ФИО</th>
                <th scope="col">Дата рождения</th>
                <th scope="col">Адрес</th>
                <th scope="col">Категория</th>
                <th scope="col">Статус ЛД</th>
                <th scope="col">Движение ЛД</th>
                <th scope="col">Изменение ЛД</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <th scope="row">{{ ld.ipd }}</th>
                <td>{{ ld.client }}</td>
                <td>{{ ld.client.bday }}</td>
                <td>{{ ld.client.address }}</td>
                <td>{{ ld.category }}</td>
                <td>{{ ld.control }}</td>
                {% if ld.control.check_mark == 'в архиве'%}
                <td></td>
                {% elif ld.control.check_mark == 'передано в др. уч.' %}
                <td>{{ ld.info }}</td>
                {% else %}
                <td>{{ ld.spec }}</td>
                {% endif %}
                <td>
                    <a href="{% url 'main:edit_ld' ld.id %}" class="btn btn-info">Перейти в форму редактирования</a>
                </td>
            </tr>
        </tbody>
        </table>
    </div>
</div>
{% endblock content %}

main/templates/main/newclient.html
{% extends "main/base.html" %}
{% block title %}
    {% block name %} | Добавление нового клиента{% endblock name %}
{% endblock title%}
{% block menu %}
    <a class="navbar-brand" href="{% url 'main:main' %}">Поиск ЛД</a>
    <a class="navbar-brand" href="{% url 'main:newld' %}">Добавить новое ЛД</a>
    <a class="navbar-brand" href="{% url 'accountability:accountability' %}">Отчетность</a>
{% endblock menu %}
{% block content %}
<div class="container">
    <div id="form">Форма добавления клиента</div><br>
    <hr>
    <form action="{% url 'main:newclient' %}" method='post'>
        {% csrf_token %}
        <div id="form_style">
        {{ form.as_p }}
            <button class="btn btn-lg btn-primary btn-block" name="submit">Добавить клиента</button>
        </div>
    </form>
</div>
{% endblock content %}

main/templates/main/newld.html
{% extends "main/base.html" %}
{% block title %}
    {% block name %} | Добавление нового ЛД{% endblock name %}
{% endblock title%}
{% block menu %}
    <a class="navbar-brand" href="{% url 'main:main' %}">Поиск ЛД</a>
    <a class="navbar-brand" href="{% url 'main:newclient' %}">Добавить нового клиента</a>
    <a class="navbar-brand" href="{% url 'accountability:accountability' %}">Отчетность</a>
{% endblock menu %}
{% block content %}
<div class="container">
<div id="form">Форма добавления ЛД</div><br>
    <hr>
    <form action="{% url 'main:newld' %}" method='post'>
        {% csrf_token %}
        <div id="form_style">
        {{ form.as_p }}
            <button class="btn btn-lg btn-primary btn-block" name="submit" style="width: 100%;">Добавить ЛД</button>
        </div>
    </form>
</div>
{% endblock content %}

main/templates/main/queryld.html
{% extends "main/base.html" %}
{% block title %}
    {% block name %} | Запрос ЛД{% endblock name %}
{% endblock title%}
{% block menu %}
    <a class="navbar-brand" href="{% url 'main:main' %}">Поиск ЛД</a>
    <a class="navbar-brand" href="{% url 'main:ldinjob' %}">ЛД в работе</a>
{% endblock menu %}
{% block content %}
<div class="container">
    <div id="form">Форма запроса ЛД</div><br>
    <hr>
    <form action="" method='post'>
        {% csrf_token %}
        <div id="form_style">
            <p>
                <select name="query_client" required="" id="id_query_client">
                    <option value="" selected="">---------</option>
                {% for q in query %}
                    <option value="{{ q.id }}">{{ q.ipd }} {{ q.client }}</option>
                {% endfor %}
                </select>

                <span class="helptext">* Личное дело</span>
            </p>
            <p>
                <input type="text" name="query_date" required="" id="id_query_date">
                <span class="helptext">* Дата запроса (01.01.2019)</span>
            </p>
            <p>
                <input type="checkbox" name="query_ld" id="id_query_ld">
                <span class="helptext">* Статус запроса</span>
            </p>
            <p>
                <select name="query_spec" required="" id="id_query_spec">
                {% for u in users %}
                    <option value="{{ u.id }}">{{ u.fio }}</option>
                    {% endfor %}
                </select> <span class="helptext">* Специалист</span>
            </p>
            <button class="btn btn-lg btn-primary btn-block" name="submit" >Запрос</button>
        </div>
    </form>
    <!--<form action="{% url 'main:queryld' %}" method='post'>-->
        <!--{% csrf_token %}-->
        <!--<div id="form_style">-->
        <!--{{ form.as_p }}-->
            <!--<button class="btn btn-lg btn-primary btn-block" name="submit" style="width: 100%;">Запрос ЛД</button>-->
        <!--</div>-->
    <!--</form>-->

    <br><hr><p>Внимание, все поля помеченные звездочкой, обязательны для заполнения.</p>
</div>
{% endblock content %}
{% block scripts %}
<script>
$('form').on('click', 'p[name="submit"]', function () {
var data = $(this).parents('form').serialize();

    $.ajax({
        url: "queryld",
        type:"GET",
        data: form.serialize(),
        dataType:"html",
        beforeSend:funcBeforeinfoNewItemsProdaj,
        success: funcSuccessinfoNewItemsProdaj
      });
});
</script>
{% endblock scripts %}

main/templates/main/spec.html
{% extends "main/base.html" %}
{% block title %}
    {% block name %} | Рабочее место специалиста{% endblock name %}
{% endblock title%}
{% block menu %}
    <a class="navbar-brand" href="{% url 'main:queryld' %}">Запрос ЛД</a>
    <!--<a class="navbar-brand" href="">Вернуть ЛД</a>-->
    <a class="navbar-brand" href="{% url 'main:ldinjob' %}">ЛД в работе</a>
{% endblock menu %}
{% block content %}
<div class="container-fluid">
    <div class="row" align="right">
        <form action="{% url 'main:search' %}" method="post">
            <div class="col-md-7" style="margin-left: 10px; width: auto;">
                {% csrf_token %}
                {{ form.as_p }}
                <p>
                    <label for="search"></label>
                    <input class="form-control" id="search" type="text" name="search" value="{{ search }}" size="100"
                           placeholder="Поиск личного дела по ФИО или ИПД, например: Иванов Иван Петрович или 123456"
                           title="Поиск личного дела по ФИО или ИПД, например: Иванов Иван Петровичили или 123456">
                </p>
            </div>
            <div class="col-md-1" style="float: right;">
                <button class="btn btn-lg btn-primary btn-block" type="submit">Найти</button>
            </div>
        </form>
    </div>
    <hr>
    <div class="row" align="left">
        <div class="col-md-11">
        {% for i in data_search %}
            <table class="table">
                <thead class="thead-dark">
                    <tr>
                        <th scope="col">ИПД</th>
                        <th scope="col">Фамилия</th>
                        <th scope="col">Имя</th>
                        <th scope="col">Отчество</th>
                        <th scope="col">Дата рождения</th>
                        <th scope="col">Адрес</th>
                        <th scope="col">Категория</th>
                        <th scope="col">Статус ЛД</th>
                        <th scope="col">Движение ЛД</th>
                        <th scope="col">Изменение ЛД</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <th scope="row">{{ i.ipd }}</th>
                        <td>{{ i.client.last_name }}</td>
                        <td>{{ i.client.first_name }}</td>
                        <td>{{ i.client.middle_name }}</td>
                        <td>{{ i.client.bday }}</td>
                        <td>{{ i.client.address }}</td>
                        <td>{{ i.category }}</td>
                        <td>{{ i.control }}</td>
                        {% if i.control.check_mark == 'в архиве'%}
                        <td></td>
                        {% elif i.control.check_mark == 'передано в др. уч.' %}
                        <td>{{ i.info }}</td>
                        {% else %}
                        <td>{{ i.spec }}</td>
                        {% endif %}
                        <td>
                            <a href="{% url 'main:queryld' %}" class="btn btn-info" onclick="">Запросить ЛД</a>
                        </td>
                    </tr>
                </tbody>
            </table>
        {% endfor %}
        </div>
        <div id="specialist" onclick="return false" class="col-md-1" style="display:none">
            {% include 'main/queryld.html' %}
        </div>
    </div>
</div>
{% endblock content %}
{% block script %}
<script>
$('#sel').on('click',function(){
        $('#specialist').show();
});
</script>
{% endblock script %}